name: Build and Deploy

on:
  schedule:
    - cron: '*/10 * * * *'      # ogni 10 minuti
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: write           # permette il push su gh-pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install --omit=dev

      - name: Run prerender script
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: false

