name: Build and Deploy

on:
  schedule:
    - cron: '*/10 * * * *'      # ogni 10 minuti
  workflow_dispatch:            # avvio manuale dal tab Actions
  push:
    branches: [ main ]          # rigenera quando fai commit su main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm ci --omit=dev

      - name: Run prerender script
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: false      # cancella i vecchi file
